name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Lint"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup gdtoolkit
        uses: Scony/godot-gdscript-toolkit@e9ec1f52d9c837dba440987ba50540f14beb7cad

      - name: Lint
        run: find . -iname *.gd -not -ipath './addons/*' | grep -v wwise_ids.gd | xargs gdlint

  formatting:
    runs-on: ubuntu-latest
    name: "Formatting"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup gdtoolkit
        uses: Scony/godot-gdscript-toolkit@e9ec1f52d9c837dba440987ba50540f14beb7cad

      - name: Check formatting
        run: find . -iname *.gd -not -ipath './addons/*' | grep -v wwise_ids.gd | xargs gdformat --check